export enum ManageProductFields {
  Name = 'name',
  Price = 'price',
  OldPrice = 'oldPrice',
  Artical = 'artical',
  Desc = 'desc',
  ShortDesc = 'shortDesc',
  Keywords = 'keywords',
  Available = 'available',
  Color = 'color',
  Category = 'category',
  Images = 'images',
  Tags = 'tags',
  Url = 'url',
}
